spring:
  application:
    #name: application-dev
nacos:
  config:
    server-addr: 192.168.149.11:8848
    namespace: 503d472a-8616-495a-9c19-63055d239b22
    #data-id: application-dev.yml
    #auto-refresh: true
    username: nacos
    password: nacos


# 日志配置路径和名称
log:
  path: /Users/sefo/Downloads/logs
  name: project